"""
Backup & Sync Management Logic
Supports local directory backup, scheduling cron jobs, and syncing via Rclone to Google Drive.
"""
from pathlib import Path
import os
import json
import shutil
import subprocess
import zipfile
from datetime import datetime

CONFIG_FILE = Path("/opt/copanel/config/backup_config.json")

class BackupManager:
    @staticmethod
    def load_config() -> dict:
        """Loads Backup and Rclone configurations from disk."""
        if CONFIG_FILE.exists():
            try:
                with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception:
                pass
        return {
            "source_dir": "",
            "rclone_remote_name": "gdrive",
            "rclone_folder": "CoPanel-Backups",
            "google_drive_client_id": "",
            "google_drive_client_secret": "",
            "google_drive_refresh_token": "",
            "cron_expression": "0 0 * * *",
            "backup_tasks": [],
            "sync_rules": []
        }

    @staticmethod
    def save_config(cfg: dict) -> bool:
        """Saves Backup and Rclone configurations to disk."""
        try:
            CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)
            with open(CONFIG_FILE, "w", encoding="utf-8") as f:
                json.dump(cfg, f, indent=2, ensure_ascii=False)
            
            # Generate the watcher script and restart its systemd daemon
            BackupManager.generate_rclone_watcher()
            # Register cron jobs
            BackupManager.setup_cron()
            return True
        except Exception:
            return False

    @staticmethod
    def generate_rclone_watcher() -> bool:
        """Generates the rclone watcher script and systemd service."""
        cfg = BackupManager.load_config()
        rules = cfg.get("sync_rules", [])
        if not rules:
            return False

        # Build inotify monitoring dirs
        monitor_dirs = set()
        for r in rules:
            lp = r.get("local_path")
            if lp:
                p = os.path.dirname(lp)
                if p and p != "/":
                    monitor_dirs.add(p)

        if not monitor_dirs:
            monitor_dirs.add("/home/Docker")

        monitor_dirs_str = " ".join(f'"{d}"' for d in monitor_dirs)

        # Build sync commands inside sync_function
        sync_cmds = []
        for r in rules:
            lp = r.get("local_path")
            rp = r.get("remote_path")
            t = r.get("type", "static_files")

            if not lp or not rp:
                continue

            if t == "database":
                sync_cmds.append(f'    rclone sync "{lp}" "{rp}" --metadata --inplace --transfers 1 --checkers 2 --use-mmap')
            else:
                sync_cmds.append(f'    rclone sync "{lp}" "{rp}" --size-only --transfers 1 --checkers 2')

        sync_cmds_str = "\n".join(sync_cmds)

        script_content = f"""#!/bin/bash

# Generated by CoPanel
MONITOR_DIRS=({monitor_dirs_str})

sync_function() {{
    echo "--- Phát hiện thay đổi, bắt đầu gom dữ liệu và đồng bộ: \\$(date) ---"
{sync_cmds_str}
    echo "--- Đồng bộ hoàn tất lúc \\$(date) ---"
}}

# Theo dõi sự thay đổi
inotifywait -m -r -e modify,create,delete,move "\\${{MONITOR_DIRS[@]}}" | while read path action file; do
    # Chỉ sync nếu file thay đổi nằm trong các thư mục mục tiêu
    echo "Sự kiện mới tại \\$path\\$file - Đợi 5 phút để gom dữ liệu..."
    sleep 300
    sync_function
done
"""
        try:
            # Save the file
            watcher_path = Path("/root/rclone_watcher.sh")
            watcher_path.write_text(script_content, encoding="utf-8")
            watcher_path.chmod(0o755)

            # Create the systemd service file
            service_content = f"""[Unit]
Description=Rclone Real-time Watcher for CoPanel
After=network.target

[Service]
Type=simple
ExecStart=/root/rclone_watcher.sh
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
"""
            service_path = Path("/etc/systemd/system/rclone-watcher.service")
            service_path.write_text(service_content, encoding="utf-8")

            # Reload systemd and restart
            subprocess.run(["systemctl", "daemon-reload"], check=False)
            subprocess.run(["systemctl", "enable", "rclone-watcher"], check=False)
            subprocess.run(["systemctl", "restart", "rclone-watcher"], check=False)

            return True
        except Exception:
            return False

    @staticmethod
    def backup_and_sync() -> dict:
        """Zips source directory and uploads using Rclone."""
        cfg = BackupManager.load_config()
        src = cfg.get("source_dir")
        if not src or not Path(src).exists():
            return {"status": "error", "message": f"Target folder {src} does not exist."}

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_dir = Path("/opt/copanel/backups")
        backup_dir.mkdir(parents=True, exist_ok=True)
        
        zip_path = backup_dir / f"backup_{timestamp}.zip"
        
        try:
            # Create local backup zip
            with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
                source_path = Path(src)
                for file_path in source_path.rglob('*'):
                    if file_path.is_file():
                        zipf.write(file_path, file_path.relative_to(source_path))
            
            # Sync to Google Drive via Rclone
            remote = cfg.get("rclone_remote_name", "gdrive")
            rclone_folder = cfg.get("rclone_folder", "CoPanel-Backups")
            
            if shutil.which("rclone") and cfg.get("google_drive_refresh_token"):
                # Update/Create rclone config on the fly
                rc_conf = Path("/root/.config/rclone/rclone.conf")
                rc_conf.parent.mkdir(parents=True, exist_ok=True)
                
                conf_data = f"[{remote}]\ntype = drive\n"
                if cfg.get("google_drive_client_id"):
                    conf_data += f"client_id = {cfg.get('google_drive_client_id')}\n"
                if cfg.get("google_drive_client_secret"):
                    conf_data += f"client_secret = {cfg.get('google_drive_client_secret')}\n"
                if cfg.get("google_drive_refresh_token"):
                    conf_data += f"token = {cfg.get('google_drive_refresh_token')}\n"
                
                rc_conf.write_text(conf_data)
                
                # Copy file to remote
                subprocess.run(["rclone", "copy", str(zip_path), f"{remote}:{rclone_folder}"], timeout=300)
                
            return {"status": "success", "file": str(zip_path), "message": "Backup generated and synced successfully!"}
        except Exception as e:
            return {"status": "error", "message": str(e)}

    @staticmethod
    def list_cron_jobs() -> list:
        """Retrieves CoPanel backup crons from active crontab."""
        try:
            res = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
            if res.returncode == 0:
                lines = res.stdout.strip().split("\n")
                results = []
                for line in lines:
                    if "backup_and_sync" in line:
                        parts = line.split()
                        if len(parts) >= 5:
                            expression = " ".join(parts[:5])
                            results.append({
                                "expression": expression,
                                "command": line,
                                "raw": line
                            })
                        else:
                            results.append({
                                "expression": "N/A",
                                "command": line,
                                "raw": line
                            })
                return results
        except Exception:
            pass
        return []

    @staticmethod
    def list_backups() -> list:
        """Scan /opt/copanel/backups and returns local backup files."""
        backup_dir = Path("/opt/copanel/backups")
        if not backup_dir.exists():
            return []
        
        backups = []
        try:
            for item in backup_dir.iterdir():
                if item.is_file() and item.suffix == ".zip":
                    stat = item.stat()
                    backups.append({
                        "name": item.name,
                        "path": str(item),
                        "size": stat.st_size,
                        "modified": stat.st_mtime
                    })
            backups.sort(key=lambda x: x["modified"], reverse=True)
        except Exception:
            pass
        return backups

    @staticmethod
    def delete_backup(filename: str) -> bool:
        """Deletes a backup file by name from /opt/copanel/backups."""
        try:
            p = Path("/opt/copanel/backups") / filename
            if p.exists() and p.is_file():
                p.unlink()
                return True
        except Exception:
            pass
        return False

    @staticmethod
    def setup_cron(cron_expr: str = "") -> bool:
        """Saves all backup tasks into crontab."""
        try:
            cfg = BackupManager.load_config()
            tasks = cfg.get("backup_tasks", [])
            
            res = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
            current_lines = []
            if res.returncode == 0:
                current_lines = [line for line in res.stdout.split("\n") if line and "backup_and_sync" not in line and "run_backup_task" not in line]

            if cfg.get("source_dir") and cfg.get("cron_expression"):
                expr = cfg.get("cron_expression")
                cmd = f"{expr} /opt/copanel/venv/bin/python -c 'import sys; sys.path.append(\"/opt/copanel/backend\"); from modules.backup_manager.logic import BackupManager; BackupManager.backup_and_sync()' >> /opt/copanel/logs/backup.log 2>&1"
                current_lines.append(cmd)

            for t in tasks:
                t_id = t.get("id")
                expr = t.get("cron_expression", "0 0 * * *")
                if not t_id or not expr:
                    continue
                cmd = f"{expr} /opt/copanel/venv/bin/python -c 'import sys; sys.path.append(\"/opt/copanel/backend\"); from modules.backup_manager.logic import BackupManager; BackupManager.run_backup_task(\"{t_id}\")' >> /opt/copanel/logs/backup_{t_id}.log 2>&1"
                current_lines.append(cmd)

            new_crontab = "\n".join(current_lines) + "\n"
            subprocess.run(["crontab", "-"], input=new_crontab, text=True)
            return True
        except Exception:
            return False

    @staticmethod
    def delete_cron() -> bool:
        """Removes active CoPanel backup crons."""
        try:
            res = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
            if res.returncode == 0:
                current_lines = [line for line in res.stdout.split("\n") if line and "backup_and_sync" not in line and "run_backup_task" not in line]
                new_crontab = "\n".join(current_lines) + "\n"
                subprocess.run(["crontab", "-"], input=new_crontab, text=True)
            return True
        except Exception:
            return False

    @staticmethod
    def run_backup_task(task_id: str) -> dict:
        """Executes a specific backup task by ID from backup_config.json."""
        cfg = BackupManager.load_config()
        tasks = cfg.get("backup_tasks", [])
        task = next((t for t in tasks if t.get("id") == task_id), None)
        
        if not task:
            return {"status": "error", "message": f"Backup task {task_id} not found."}
            
        src = task.get("source_dir")
        if not src or not Path(src).exists():
            return {"status": "error", "message": f"Target folder {src} does not exist."}
            
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_dir = Path("/opt/copanel/backups")
        backup_dir.mkdir(parents=True, exist_ok=True)
        
        zip_path = backup_dir / f"backup_{task_id}_{timestamp}.zip"
        
        try:
            with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
                source_path = Path(src)
                for file_path in source_path.rglob('*'):
                    if file_path.is_file():
                        zipf.write(file_path, file_path.relative_to(source_path))
                        
            remote = cfg.get("rclone_remote_name", "gdrive")
            rclone_folder = task.get("rclone_folder", "CoPanel-Backups")
            
            if shutil.which("rclone") and cfg.get("google_drive_refresh_token"):
                rc_conf = Path("/root/.config/rclone/rclone.conf")
                rc_conf.parent.mkdir(parents=True, exist_ok=True)
                
                conf_data = f"[{remote}]\ntype = drive\n"
                if cfg.get("google_drive_client_id"):
                    conf_data += f"client_id = {cfg.get('google_drive_client_id')}\n"
                if cfg.get("google_drive_client_secret"):
                    conf_data += f"client_secret = {cfg.get('google_drive_client_secret')}\n"
                if cfg.get("google_drive_refresh_token"):
                    conf_data += f"token = {cfg.get('google_drive_refresh_token')}\n"
                
                rc_conf.write_text(conf_data)
                subprocess.run(["rclone", "copy", str(zip_path), f"{remote}:{rclone_folder}"], timeout=300)
                
            return {"status": "success", "file": str(zip_path), "message": f"Task {task_id} backup generated and synced successfully!"}
        except Exception as e:
            return {"status": "error", "message": str(e)}
